print('This program will find the quotient, difference, product and sum of 2 numbers')
num1 = input("First number:")
num2 = input("Second number:")
quotient = float(num1) / float(num2)
difference = int(num1) - int(num2)
product = float(num1) * float(num2)
sum = int(num1) + int(num2)
print("The quotient is: " + str(quotient))
print("The difference is: " + str(difference))
print("The product is: " + str(product))
print("The sum is: " + str(sum))